# site name
prefixName: ねこ 
siteName: catsgarden
# favicon and site master avatar
favicon: /img/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://catsgarden.top
description: めあくあてぇてぇ
cdn: https://cdn.jsdelivr.net/gh/catsgarden99/cdn@1.4
pjax: 1
# 1开启
mathjax: 0

notice: 只会喊咩夸贴贴的zz
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    DD: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
#  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/catsgarden99/cdn@1.4/img/cover/mctower.png


# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass:

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/8176608, title: Bilibili, desc: 我的b站, img: /img/startdash/bilibili.jpg}
  #- {url: https://space.bilibili.com/8176608, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: catsgarden的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 06/17/2020

#social  url, img PC端配置
social:
  github: {url: https://github.com/catsgarden99, img: /img/social/github.jpg}
  sina: {url: https://weibo.com/6824682306/profile?topnav=1&wvr=6, img: /img/social/sina.jpg}
  wangyiyun: {url: https://music.163.com/playlist?id=161622176&userid=128923128, img: /img/social/wangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  #email: {url: https://weibo.com/6824682306/profile?topnav=1&wvr=6, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/donate/WeChanQR.png, img: /img/social/wechat.jpg}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/catsgarden99, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/6824682306/profile?topnav=1&wvr=6, fa: fa-weibo, color: dd4b39}
#  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  #paypal: https://www.paypal.me/hojuncn
  alipay: /img/donate/AliPayQR.jpg
  wechat: /img/donate/WeChanQR.png
  wechatSQ: /img/donate/WeChanSQ.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.1/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/catsgarden99/cdn@1.0
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2704052220
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.5
  mutex: true

# Valine
valine: true
v_appId: VK7GWKKIPktqsXTRGvHHo3FS-gzGzoHsz
v_appKey: IekNgNgrOTQmq89UFAEz0YwB

